[package]
name = "instant-rust"
version = "0.1.0"
authors = ["Marek Puzyna <puzynamarek97@gmail.com>"]

build = "src/build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.16.0"
regex = "1.0.5"

[build-dependencies]
lalrpop = "0.16.0"